### ISSUE TITLE
Hänger sig

### ISSUE THREAD

**Issue by krantzet** [kanflo/tvos-barnkanalen#1]
Stort tack för denna, otroligt smidig att ha. Den hänger sig dock vid uppstart om den hamnat i bakgrunden och Apple TVn gått ner i sleepmode och man måste tvångsavsluta den innan den startar igen. Vet inte om det är enkelt att lägga en omstart av streamen så fort programmet blir aktivt, men hade varit sjukt tacksam :)

Och tack igen !

**Comment by kanflo** [comment]
Kul att den kom till användning i åtminståne en annan barnfamilj :D Jag skall kika på hur man kan fixa den här buggen.

**Comment by kanflo** [comment]
@krantzet, jag gjorde ett grishack för att få igång strömmen igen. Berätta gärna om det funkar.
