### ISSUE TITLE
Fungerar inte efter uppgradering till TVOS 10.3

### ISSUE THREAD

**Issue by krantzet** [kanflo/tvos-barnkanalen#2]
Efter uppgradering till TVOS 10.3 / XCode 8.3 fungerar inte längre appen.
Det fungerar fint att Sideloada den till Apple TV, men när strömmen ska öppnas visar den bara en svart bakgrund och en snurrande snurra.

**Comment by kanflo** [comment]
Kidsen har växt ifrån barnkanalen och förmodligen har all kod ruttnat de senaste åren så det blir 'won't fix' på hela repot.
